# DataManager Demo

Quick walkthrough of the enhanced DataManager features for market data handling.

In [1]:
from st.data import DataManager, DownloadRequest, StockInfo
import pandas as pd

# Initialize DataManager
dm = DataManager()

## 1. Download Single Stock

In [2]:
# Download Apple stock data
req = DownloadRequest(
    ticker="AAPL",
    start_date="2023-01-01",
    end_date="2024-12-31",
    save=True
)

df = dm.download_stock_data(req)
print(f"Downloaded {len(df)} rows")
df.head()

2025-12-09 23:12:45 - st.data.data_manager - INFO - Downloading AAPL from 2023-01-01 to 2024-12-31
2025-12-09 23:12:45 - st.data.data_manager - INFO - Saved AAPL data to /Users/coolmajor/PycharmProjects/systematic_trading/data/AAPL.csv
2025-12-09 23:12:45 - st.data.data_manager - INFO - Downloaded 501 rows for AAPL
Downloaded 501 rows

                  Open        High         Low       Close     Volume
Date
2023-01-03  128.343780  128.954561  122.324586  123.211212  112117500
2023-01-04  125.004147  126.747845  123.221050  124.482025   89113600
2023-01-05  125.240583  125.871071  122.905811  123.161942   80962700
2023-01-06  124.137254  128.353637  123.033897  127.693596   87754700
2023-01-09  128.530934  131.427242  127.959553  128.215683   70790800

## 2. Batch Download Multiple Stocks

In [3]:
# Download multiple tickers efficiently
tickers = ["AAPL", "GOOGL", "MSFT", "TSLA"]
requests = [DownloadRequest(ticker=t, save=True) for t in tickers]

data = dm.download_multiple_stocks(requests, parallel=True)

for ticker, df in data.items():
    print(f"{ticker}: {len(df)} rows")

2025-12-09 23:12:45 - st.data.data_manager - INFO - Batch downloading 4 tickers
2025-12-09 23:12:46 - st.data.data_manager - INFO - Saved AAPL data to /Users/coolmajor/PycharmProjects/systematic_trading/data/AAPL.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Downloaded 1995 rows for AAPL
2025-12-09 23:12:46 - st.data.data_manager - INFO - Saved GOOGL data to /Users/coolmajor/PycharmProjects/systematic_trading/data/GOOGL.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Downloaded 1995 rows for GOOGL
2025-12-09 23:12:46 - st.data.data_manager - INFO - Saved MSFT data to /Users/coolmajor/PycharmProjects/systematic_trading/data/MSFT.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Downloaded 1995 rows for MSFT
2025-12-09 23:12:46 - st.data.data_manager - INFO - Saved TSLA data to /Users/coolmajor/PycharmProjects/systematic_trading/data/TSLA.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Downloaded 1995 rows for TSLA
AAPL: 1995 rows
GOOGL: 1995 rows
MSFT: 1995 rows
TSLA: 1995 rows

## 3. Load Saved Data

In [4]:
# Load previously downloaded data
aapl_data = dm.load_data("AAPL")
print(f"Loaded {len(aapl_data)} rows")
aapl_data.tail()

2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for AAPL from /Users/coolmajor/PycharmProjects/systematic_trading/data/AAPL.csv
Loaded 1995 rows

                  Open        High         Low       Close    Volume
Date
2025-12-02  283.000000  287.399994  282.630005  286.190002  53669500
2025-12-03  286.200012  288.619995  283.299988  284.149994  43538700
2025-12-04  284.100006  284.730011  278.589996  280.700012  43989100
2025-12-05  280.540009  281.140015  278.049988  278.779999  47265800
2025-12-08  278.130005  279.670013  276.149994  277.890015  38140000

## 4. Get Close Prices for Multiple Stocks

In [5]:
# Get close prices DataFrame for portfolio analysis
tickers = ["AAPL", "GOOGL", "MSFT"]
close_prices = dm.get_close_prices(
    tickers,
    start_date="2024-01-01",
    end_date="2024-12-31"
)

print(close_prices.shape)
close_prices.head()

2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for AAPL from /Users/coolmajor/PycharmProjects/systematic_trading/data/AAPL.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for GOOGL from /Users/coolmajor/PycharmProjects/systematic_trading/data/GOOGL.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for MSFT from /Users/coolmajor/PycharmProjects/systematic_trading/data/MSFT.csv
(252, 3)

                  AAPL       GOOGL        MSFT
Date
2024-01-02  183.903244  137.133850  365.421600
2024-01-03  182.526230  137.878235  365.155579
2024-01-04  180.208130  135.367188  362.534668
2024-01-05  179.484940  134.712158  362.347473
2024-01-08  183.823990  137.798813  369.185516

## 5. Get Stock Information

In [6]:
# Fetch stock metadata
info = dm.get_stock_info("AAPL")
print(f"Name: {info.name}")
print(f"Sector: {info.sector}")
print(f"Currency: {info.currency}")
print(f"Exchange: {info.exchange}")

Name: Apple Inc.
Sector: Technology
Currency: USD
Exchange: NMS

## 6. Check Data Freshness

In [7]:
# Check if data exists
print(f"AAPL data exists: {dm.data_exists('AAPL')}")

# Get date range of stored data
date_range = dm.get_data_date_range("AAPL")
print(f"Date range: {date_range}")

# Check if data is stale (older than 1 day)
is_stale = dm.is_data_stale("AAPL", max_days_old=1)
print(f"Data is stale: {is_stale}")

AAPL data exists: True
2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for AAPL from /Users/coolmajor/PycharmProjects/systematic_trading/data/AAPL.csv
Date range: ('2018-01-02', '2025-12-08')
2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for AAPL from /Users/coolmajor/PycharmProjects/systematic_trading/data/AAPL.csv
Data is stale: False

## 7. Update Stale Data

In [8]:
# Auto-update stale tickers
tickers = ["AAPL", "GOOGL", "MSFT", "TSLA"]
updated = dm.update_stale_data(tickers, max_days_old=1)
print(f"Updated {len(updated)} tickers: {list(updated.keys())}")

2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for AAPL from /Users/coolmajor/PycharmProjects/systematic_trading/data/AAPL.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for GOOGL from /Users/coolmajor/PycharmProjects/systematic_trading/data/GOOGL.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for MSFT from /Users/coolmajor/PycharmProjects/systematic_trading/data/MSFT.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for TSLA from /Users/coolmajor/PycharmProjects/systematic_trading/data/TSLA.csv
2025-12-09 23:12:46 - st.data.data_manager - INFO - Updated 0 stale tickers
Updated 0 tickers: []

## 8. Get OHLCV Data with Date Filtering

In [9]:
# Get OHLCV data for specific date range
ohlcv = dm.get_ohlcv(
    "AAPL",
    start_date="2024-06-01",
    end_date="2024-12-31"
)

print(f"Shape: {ohlcv.shape}")
ohlcv.head()

2025-12-09 23:12:46 - st.data.data_manager - INFO - Loaded 1995 rows for AAPL from /Users/coolmajor/PycharmProjects/systematic_trading/data/AAPL.csv
Shape: (147, 5)

                  Open        High         Low       Close    Volume
Date
2024-06-03  191.598672  193.674584  191.221246  192.721054  50080500
2024-06-04  193.326947  194.002367  191.727807  193.038910  47471400
2024-06-05  194.081799  195.571680  193.555376  194.548630  54156800
2024-06-06  194.369843  195.174376  192.860093  193.167999  41181800
2024-06-07  193.336873  195.611433  192.830319  195.561768  53103900

## 9. Storage Management

In [10]:
# List all available tickers
available = dm.list_available_tickers()
print(f"Available tickers: {available}")

# Get storage info
storage = dm.get_storage_info()
print(f"\nStorage Info:")
print(f"Directory: {storage['data_dir']}")
print(f"Files: {storage['num_files']}")
print(f"Total size: {storage['total_size_mb']} MB")

Available tickers: ['AAPL', 'GOOGL', 'MSFT', 'TSLA']

Storage Info:
Directory: /Users/coolmajor/PycharmProjects/systematic_trading/data
Files: 4
Total size: 0.71 MB

## 10. Cleanup

In [11]:
# Delete specific ticker data
# dm.delete_data("TSLA")
# print(f"Available after deletion: {dm.list_available_tickers()}")